# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alert-manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alert-manager.proto',
  package='unary',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x61lert-manager.proto\x12\x05unary\"#\n\x11NodeStatusRequest\x12\x0e\n\x06nodeIP\x18\x01 \x01(\t\"C\n\x12NodeStatusResponse\x12\x14\n\x0cresponseCode\x18\x01 \x01(\x05\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t2X\n\x13\x41lertManagerService\x12\x41\n\x08NodeDown\x12\x18.unary.NodeStatusRequest\x1a\x19.unary.NodeStatusResponse\"\x00\x62\x06proto3'
)




_NODESTATUSREQUEST = _descriptor.Descriptor(
  name='NodeStatusRequest',
  full_name='unary.NodeStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeIP', full_name='unary.NodeStatusRequest.nodeIP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=65,
)


_NODESTATUSRESPONSE = _descriptor.Descriptor(
  name='NodeStatusResponse',
  full_name='unary.NodeStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='unary.NodeStatusResponse.responseCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='unary.NodeStatusResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['NodeStatusRequest'] = _NODESTATUSREQUEST
DESCRIPTOR.message_types_by_name['NodeStatusResponse'] = _NODESTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeStatusRequest = _reflection.GeneratedProtocolMessageType('NodeStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODESTATUSREQUEST,
  '__module__' : 'alert_manager_pb2'
  # @@protoc_insertion_point(class_scope:unary.NodeStatusRequest)
  })
_sym_db.RegisterMessage(NodeStatusRequest)

NodeStatusResponse = _reflection.GeneratedProtocolMessageType('NodeStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODESTATUSRESPONSE,
  '__module__' : 'alert_manager_pb2'
  # @@protoc_insertion_point(class_scope:unary.NodeStatusResponse)
  })
_sym_db.RegisterMessage(NodeStatusResponse)



_ALERTMANAGERSERVICE = _descriptor.ServiceDescriptor(
  name='AlertManagerService',
  full_name='unary.AlertManagerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=136,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='NodeDown',
    full_name='unary.AlertManagerService.NodeDown',
    index=0,
    containing_service=None,
    input_type=_NODESTATUSREQUEST,
    output_type=_NODESTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALERTMANAGERSERVICE)

DESCRIPTOR.services_by_name['AlertManagerService'] = _ALERTMANAGERSERVICE

# @@protoc_insertion_point(module_scope)
