# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x07monitor\"@\n\x10HeartBeatWrapper\x12,\n\x10node_status_desc\x18\x01 \x01(\x0b\x32\x12.monitor.HeartBeat\"[\n\tHeartBeat\x12\x0f\n\x07node_ip\x18\x01 \x01(\t\x12\x13\n\x0bnode_status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x15\n\rresponse_time\x18\x04 \x01(\t\"*\n\x14HeartBeatReceivedACK\x12\x12\n\nsuccessACK\x18\x01 \x01(\t2R\n\x07Monitor\x12G\n\x10PersistHeartbeat\x12\x12.monitor.HeartBeat\x1a\x1d.monitor.HeartBeatReceivedACK\"\x00\x62\x06proto3')



_HEARTBEATWRAPPER = DESCRIPTOR.message_types_by_name['HeartBeatWrapper']
_HEARTBEAT = DESCRIPTOR.message_types_by_name['HeartBeat']
_HEARTBEATRECEIVEDACK = DESCRIPTOR.message_types_by_name['HeartBeatReceivedACK']
HeartBeatWrapper = _reflection.GeneratedProtocolMessageType('HeartBeatWrapper', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATWRAPPER,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.HeartBeatWrapper)
  })
_sym_db.RegisterMessage(HeartBeatWrapper)

HeartBeat = _reflection.GeneratedProtocolMessageType('HeartBeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.HeartBeat)
  })
_sym_db.RegisterMessage(HeartBeat)

HeartBeatReceivedACK = _reflection.GeneratedProtocolMessageType('HeartBeatReceivedACK', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRECEIVEDACK,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.HeartBeatReceivedACK)
  })
_sym_db.RegisterMessage(HeartBeatReceivedACK)

_MONITOR = DESCRIPTOR.services_by_name['Monitor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEARTBEATWRAPPER._serialized_start=26
  _HEARTBEATWRAPPER._serialized_end=90
  _HEARTBEAT._serialized_start=92
  _HEARTBEAT._serialized_end=183
  _HEARTBEATRECEIVEDACK._serialized_start=185
  _HEARTBEATRECEIVEDACK._serialized_end=227
  _MONITOR._serialized_start=229
  _MONITOR._serialized_end=311
# @@protoc_insertion_point(module_scope)
