# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentinel-comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentinel-comm.proto',
  package='stream',
  syntax='proto3',
  serialized_options=b'\n\017org.node.protosP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13sentinel-comm.proto\x12\x06stream\"\x14\n\x12healthCheckRequest\"\"\n\x10healthCheckReply\x12\x0e\n\x06status\x18\x01 \x01(\t2[\n\x12SentinelMonitoring\x12\x45\n\x0bhealthCheck\x12\x1a.stream.healthCheckRequest\x1a\x18.stream.healthCheckReply\"\x00\x42\x13\n\x0forg.node.protosP\x01\x62\x06proto3'
)




_HEALTHCHECKREQUEST = _descriptor.Descriptor(
  name='healthCheckRequest',
  full_name='stream.healthCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=51,
)


_HEALTHCHECKREPLY = _descriptor.Descriptor(
  name='healthCheckReply',
  full_name='stream.healthCheckReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='stream.healthCheckReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['healthCheckRequest'] = _HEALTHCHECKREQUEST
DESCRIPTOR.message_types_by_name['healthCheckReply'] = _HEALTHCHECKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

healthCheckRequest = _reflection.GeneratedProtocolMessageType('healthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREQUEST,
  '__module__' : 'sentinel_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.healthCheckRequest)
  })
_sym_db.RegisterMessage(healthCheckRequest)

healthCheckReply = _reflection.GeneratedProtocolMessageType('healthCheckReply', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREPLY,
  '__module__' : 'sentinel_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.healthCheckReply)
  })
_sym_db.RegisterMessage(healthCheckReply)


DESCRIPTOR._options = None

_SENTINELMONITORING = _descriptor.ServiceDescriptor(
  name='SentinelMonitoring',
  full_name='stream.SentinelMonitoring',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=89,
  serialized_end=180,
  methods=[
  _descriptor.MethodDescriptor(
    name='healthCheck',
    full_name='stream.SentinelMonitoring.healthCheck',
    index=0,
    containing_service=None,
    input_type=_HEALTHCHECKREQUEST,
    output_type=_HEALTHCHECKREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTINELMONITORING)

DESCRIPTOR.services_by_name['SentinelMonitoring'] = _SENTINELMONITORING

# @@protoc_insertion_point(module_scope)
