# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ggregator.proto\"f\n\x14PersistableHeartBeat\x12\x0f\n\x07node_ip\x18\x01 \x01(\t\x12\x13\n\x0bnode_status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x15\n\rresponse_time\x18\x04 \x01(\t\"?\n\x15HeartBeatPersistedACK\x12\x12\n\nsuccessACK\x18\x01 \x01(\t\x12\x12\n\nfailureACK\x18\x02 \x01(\t2V\n\x11\x41ggregatorService\x12\x41\n\x10PersistHeartBeat\x12\x15.PersistableHeartBeat\x1a\x16.HeartBeatPersistedACKb\x06proto3')



_PERSISTABLEHEARTBEAT = DESCRIPTOR.message_types_by_name['PersistableHeartBeat']
_HEARTBEATPERSISTEDACK = DESCRIPTOR.message_types_by_name['HeartBeatPersistedACK']
PersistableHeartBeat = _reflection.GeneratedProtocolMessageType('PersistableHeartBeat', (_message.Message,), {
  'DESCRIPTOR' : _PERSISTABLEHEARTBEAT,
  '__module__' : 'aggregator_pb2'
  # @@protoc_insertion_point(class_scope:PersistableHeartBeat)
  })
_sym_db.RegisterMessage(PersistableHeartBeat)

HeartBeatPersistedACK = _reflection.GeneratedProtocolMessageType('HeartBeatPersistedACK', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATPERSISTEDACK,
  '__module__' : 'aggregator_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeatPersistedACK)
  })
_sym_db.RegisterMessage(HeartBeatPersistedACK)

_AGGREGATORSERVICE = DESCRIPTOR.services_by_name['AggregatorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSISTABLEHEARTBEAT._serialized_start=20
  _PERSISTABLEHEARTBEAT._serialized_end=122
  _HEARTBEATPERSISTEDACK._serialized_start=124
  _HEARTBEATPERSISTEDACK._serialized_end=187
  _AGGREGATORSERVICE._serialized_start=189
  _AGGREGATORSERVICE._serialized_end=275
# @@protoc_insertion_point(module_scope)
